# Generated by Django 5.1.5 on 2025-02-03 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_article_summary_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.article')),
            ],
        ),
    ]
