# Generated by Django 5.1.5 on 2025-02-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_phonto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phonto',
            new_name='Photo',
        ),
    ]
